services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Dashboard\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Dashboard\Controller\DashboardController:
    public: true
  FriendsOfTYPO3\Dashboard\Controller\WidgetAjaxController:
    public: true
