services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Dashboard\:
    resource: '../Classes/*'


  cache.dashboard_rss:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['dashboard_rss']


  FriendsOfTYPO3\Dashboard\Controller\DashboardController:
    public: true
  FriendsOfTYPO3\Dashboard\Controller\WidgetAjaxController:
    public: true
