name: CI

on: [push, pull_request]

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        typo3: ['^9', '^10', 'dev-master']
        php: ['7.2', '7.3']
    steps:
      - uses: actions/checkout@v1
      - name: Set up PHP Version
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          php -v
      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version
      - name: Install
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json
      - name: Lint
        run: composer test:php:lint
      - name: CGL
        run: composer cgl
      - name: Unit & Functional Tests with coverage and publish code coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          ./.build/bin/paratest -p4 -c build/phpunit.xml --coverage-clover clover.xml
          ./cc-test-reporter after-build logs/coverage.xml -t clover
        env:
          CC_TEST_REPORTER_ID: 8091cc0262e618638a7d7a0825f490659f5f7ee58991b3ba5d869b724afbfb21
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root
